services:
  db:
    image: mysql:8.4.2
    ports:
      - '3306:3306'
    tty: true #必要かわかんない
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata2:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      - todolist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/src
    ports:
      - '8080:8080'
      - '5555:5555'
    depends_on:
      - db
    networks:
      - todolist
  
  app:
    build: react/
    tty: true
    volumes:
      - ./react:/src
    ports:
      - '5173:5173'
    depends_on:
      - server
    networks:
      - todolist

networks:
  todolist:
    external: true

volumes:
  mysqldata2: